### PR TITLE
Surface authentication-related API errors

### PR DESCRIPTION
**Pull request by barryhughes**
If authentication fails, show the API error message if available.

pardot-api-error

Note that when viewed via GitHub there is an apparent syntax error on [line 417](https://github.com/moderntribe/pardot/compare/fix/106707-show-api-err-msg?expand=1#diff-c21d72f2f511cce99acd0ac388d741eeR417) ‒ this is not actually a problem but a quirk in the diff viewer.

:ticket: [https://central.tri.be/issues/106707](#106707)

### CODE REVIEW

**Comment by logoscreative** [comment]
Thanks, @barryhughes! This is great. Couple of requests:

1. Can we make any links passed in the error string clickable? Like a regex on the string that wraps it in an `<a>` element. 
1. Let's make it read:

> Error: [error message]
> 
> Could not authenticate. Check the fields below and click the "Save Settings" button to try again.

**Comment by barryhughes** [comment]
For sure &ndash; will make those happen :+1:

**Comment by barryhughes** [comment]
@logoscreative ‒ round two, screenshot illustrates changes:

screenshot-2018-6-8 pardot events lab wordpress

Notes:

* WP turns out to have a handy function for making links clickable which takes care of escaping and avoiding double-linking (that doesn't matter right now, but if in future the API began returning well formed HTML in its error messages it would make this a tad more future proof)
* Separation between the API error message and the existing text is via break tags ... this was cheap and easy and avoided making changes upstream where the message is displayed

**Comment by barryhughes** [comment]
Great: will move on to next steps - thanks for the fast response :+1:

**Pull request merged**
